# Generated by Django 5.0 on 2023-12-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_cat_finch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='sighting',
            new_name='description',
        ),
    ]
