# Generated by Django 5.0 on 2023-12-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_sighting_finch_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since_date', models.DateField()),
                ('company', models.CharField(choices=[('G', 'Geico pals'), ('P', 'Pets Of America'), ('E', 'Eagle Eye')], default='G', max_length=1)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.finch')),
            ],
        ),
    ]
