# Generated by Django 5.0 on 2023-12-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
