# Generated by Django 5.0 on 2023-12-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_food_alter_insurance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='color',
            new_name='foodgroup',
        ),
        migrations.AddField(
            model_name='finch',
            name='foods',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
